"""criação das tabelas

Revision ID: 531d77b27108
Revises: 
Create Date: 2025-06-17 00:04:35.191352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531d77b27108'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.String(length=300), nullable=True))

    with op.batch_alter_table('page_visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_visits', schema=None) as batch_op:
        batch_op.drop_column('user_agent')

    with op.batch_alter_table('item_views', schema=None) as batch_op:
        batch_op.drop_column('user_agent')

    # ### end Alembic commands ###
